# Generated by Django 3.0.3 on 2020-02-23 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basvuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(max_length=11, verbose_name='Tc')),
                ('ad', models.CharField(max_length=15, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=15, verbose_name='Soyad')),
                ('tel', models.CharField(max_length=11)),
                ('maas_banka', models.CharField(choices=[('AKBANK', 'AKBANK'), ('AKTİFBANK', 'AKTİFBANK'), ('BURGAN', 'BURGAN'), ('DENİZBANK', 'DENİZBANK'), ('HALK BANKASI', 'HALK BANKASI'), ('GARANTİ BBVA', 'GARANTİ BBVA'), ('HSBC', 'HSBC'), ('ING BANK', 'ING BANK'), ('İŞ BANKASI', 'İŞ BANKASI'), ('ODEA', 'ODEA'), ('VAKIF BANK', 'VAKIF BANK'), ('QNB FİNANSBANK', 'QNB FİNANSBANK'), ('YAPI KREDİ', 'YAPI KREDİ'), ('ZİRAAT BANKASI', 'ZİRAAT BANKASI'), ('DİĞER', 'DİĞER')], max_length=20, verbose_name='Maaş Bankası')),
                ('kredi_tutari', models.CharField(choices=[('Yok', 'Yok'), ('5.000 TL', '5.000 TL'), ('10.000 TL', '10.000 TL'), ('15.000 TL', '15.000 TL'), ('20.000 TL', '20.000 TL'), ('25.000 TL', '25.000 TL'), ('30.000TL', '30.000TL'), ('35.000 TL', '35.000 TL'), ('40.000 TL', '40.000 TL'), ('45.000 TL', '45.000 TL'), ('50.000 TL', '50.000 TL'), ('60.000 TL ve üzeri', '60.000 TL ve üzeri')], max_length=18, verbose_name='Kredi Mevcut')),
                ('kredi_talebi', models.CharField(choices=[('10.000 TL', '10.000 TL'), ('15.000 TL', '15.000 TL'), ('20.000 TL', '20.000 TL'), ('25.000 TL', '25.000 TL'), ('30.000TL', '30.000TL'), ('35.000 TL', '35.000 TL'), ('40.000 TL', '40.000 TL'), ('45.000 TL', '45.000 TL'), ('50.000 TL', '50.000 TL'), ('60.000 TL ve üzeri', '60.000 TL ve üzeri')], max_length=18, verbose_name='Kredi Talebi')),
                ('city', models.CharField(choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir'), ('Diğer', 'Diğer')], max_length=20, verbose_name='Şehir')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başvuru Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=15, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=15, verbose_name='Soyad')),
                ('tel', models.CharField(max_length=11, verbose_name='Tel')),
                ('email', models.EmailField(max_length=30, verbose_name='e-Posta')),
                ('mesaj', models.TextField(max_length=500, verbose_name='Mesaj')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mesaj tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
